---

- name: enable auto security upgrades via package management strategy
  synchronize:
    src:   etc/apt/apt.conf.d
    dest: /etc/apt/

- name: find if old-style apache (httpd) service exists
  stat: path={{old_httpd_runner}}
  register: old_httpd

- name: stop old-style apache (httpd) service
  command: "{{old_httpd_runner}} stop"
  when: old_httpd.stat.exists

- name: remove old-style apache (httpd) service
  file: path={{old_httpd_runner}} state=absent

- name: install required packages (so far apache2 only)
  apt: name=apache2 state=latest

- name: ensure minimal apache dynamic modules enabled (beyond default install)
  file:
    src:          ../mods-available/{{item}}.load
    dest: /etc/apache2/mods-enabled/{{item}}.load
    force: yes
    state: link
  with_items:
    - proxy
    - proxy_http

- name: deliver apache etc/config files manageable by app teams
  synchronize:
    src:   etc/apache2/{{item}}
    dest: /etc/apache2
    recursive: yes
    delete: yes
    links: yes
    perms: yes
    times: yes
    owner: no
    group: no
  with_items:
    - conf-enabled
    - conf-available 
    - sites-enabled
    - sites-available 
  notify:
    - bounce apache

- name: replace installed welcome page with any required static content
  synchronize:
    src:   var/www/html
    dest: /var/www/
  notify:
    - bounce apache

- name: ensure new-style apache2 service running
  service: name=apache2 enabled=yes state=started

- meta: flush_handlers

- name: check expected home page is served
  uri:
    url: http://{{ inventory_hostname }}
    return_content: yes
    status_code: 200
  register: result

- name: Simplified Test of Home Page Content
  fail:
  when:  "'Welcome' not in result.content"
