---

- name: disable old-style apache (httpd) service
  service: name=httpd enabled=no state=stopped
  when: inventory_hostname in groups['old_webservers']

- name: install required packages (so far apache2 only)
  apt: name=apache2 state=latest

- name: ensure minimal apache dynamic modules enabled (beyond default install)
  file:
    src:          ../mods-available/{{item}}.load
    dest: /etc/apache2/mods-enabled/{{item}}.load
    force: yes
    state: link
  with_items:
    - proxy
    - proxy_http

- name: deliver apache etc/config files manageable by app teams
  synchronize:
    src:   etc/apache2/{{item}}
    dest: /etc/apache2
    recursive: yes
    delete: yes
    links: yes
    perms: yes
    times: yes
  with_items:
    - conf-enabled
    - conf-available 
    - sites-enabled
    - sites-available 
  notify:
    - bounce apache

- name: replace installed welcome page with any required static content
  synchronize:
    src:   var/www/html
    dest: /var/www/
  notify:
    - bounce apache

- name: ensure new-style apache2 service running
  service: name=apache2 enabled=yes state=started

- meta: flush_handlers

- name: check expected home page is served
  uri:
    url: http://{{ inventory_hostname }}
    return_content: yes
    status_code: 200
  register: result

- name: Simplified Test of Home Page Content
  fail:
  when:  "'Welcome' not in result.content"
